const enum Opcode {
	Push = 0x00,
	Pop = 0x01,
	Add = 0x02,
	Sub = 0x03,
	Mul = 0x04,
	Div = 0x05,
	Equal = 0x06,
	Jmp = 0x07,
	JmpIf = 0x08,
	Store = 0x09,
	Load = 0x0a,
	Apply = 0x0b,
	Dependency = 0x0c,
	Property = 0x0d,
	PushFrame = 0x0e,
	PopFrame = 0x0f,
	Halt = 0x10,
	BuildArray = 0x11,
	BuildObject = 0x12,
	LoadParameter = 0x13,
	Await = 0x14,
	Construct = 0x15,
	LoadMeta = 0x16,
}

const OPCODE_NAMES: Record<number, string> = {
	[Opcode.Push]: "Push",
	[Opcode.Pop]: "Pop",
	[Opcode.Add]: "Add",
	[Opcode.Sub]: "Sub",
	[Opcode.Mul]: "Mul",
	[Opcode.Div]: "Div",
	[Opcode.Equal]: "Equal",
	[Opcode.Jmp]: "Jmp",
	[Opcode.JmpIf]: "JmpIf",
	[Opcode.Store]: "Store",
	[Opcode.Load]: "Load",
	[Opcode.Apply]: "Apply",
	[Opcode.Dependency]: "Dependency",
	[Opcode.Property]: "Property",
	[Opcode.PushFrame]: "PushFrame",
	[Opcode.PopFrame]: "PopFrame",
	[Opcode.Halt]: "Halt",
	[Opcode.BuildArray]: "BuildArray",
	[Opcode.BuildObject]: "BuildObject",
	[Opcode.LoadParameter]: "LoadParameter",
	[Opcode.Await]: "Await",
	[Opcode.Construct]: "Construct",
	[Opcode.LoadMeta]: "LoadMeta",
};

const enum LabelType {
	IF_THEN = "IF_THEN",
	IF_END = "IF_END",
	FUNCTION_START = "FUNCTION_START",
	FUNCTION_END = "FUNCTION_END",
	TRY_START = "TRY_START",
	TRY_END = "TRY_END",
	CATCH_START = "CATCH_START",
	CATCH_END = "CATCH_END",
	FINALIZER_START = "FINALIZER_START",
	FINALIZER_END = "FINALIZER_END",
}

export { Opcode, LabelType, OPCODE_NAMES };
